apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld-tomcat
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: tomcat:9.0
    ports:
    - name: nodejs-port
      containerPort: 8080
